### PR TITLE
Add verbage to the readme to outline the process for importing blockchain data from a file

### PR DESCRIPTION
**Pull request by KyleMcMaster**
This PR is a WIP as I would like to add verbage for exporting the blockchain to a file as well. I was wanting to get some feedback early on my wording and any suggestions for improving before completing this feature / PR. 

I am not sure how to link to issues on github but the issue I am trying to resolve is #178.

Thanks,
-KM

### CODE REVIEW

**Comment by KyleMcMaster** [comment]
After reviewing Ryo and Monero's source I stumbled upon this:

`https://github.com/ryo-currency/ryo-currency/blob/master/src/blockchain_utilities/README.md`

Unless there are suggestions for how to improve this documentation, I will abandon this PR as the functionality I described already has existing documentation.

**Comment by psychocrypt** [comment]
thx for your PR, we will review the PR soon

**Comment by fireice-uk** [comment]
I don't see why a terse description can't be in the main readme but maybe include a link to the import?

**Comment by KyleMcMaster** [comment]
@fireice-uk Do you mean a link to the import file `https://download.ryo-currency.com/blockchain.raw`?

**Comment by fireice-uk** [comment]
I meant adding a link to [[ this file ]](https://github.com/ryo-currency/ryo-currency/blob/master/src/blockchain_utilities/README.md) in your PR

**Comment by KyleMcMaster** [comment]
@fireice-uk I've added a reference to the utilities documentation from the main readme.

**Comment by KyleMcMaster** [comment]
Any further thoughts on this PR?

**Comment by fireice-uk** [comment]
Sorry about the delay - we were busy working on another repositories. It looks, I will merge it (pending a proper split up with a table of contents since it is getting pretty long)

**Comment by KyleMcMaster** [comment]
@fireice-uk I would like to continue to contribute to the documentation if possible. Do you have recommendations for splitting out the table of contents or possibly a link to a similar repository with documentation to reference?

**Pull request merged**
